/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package risc.server;

import risc.shared.MyName;

public class App {
  public String getMessage() { return "Hello from the server for " + MyName.getName(); }
  public static void main(String[] args) {
    App a = new App();
    System.out.println(a.getMessage());
  }
}
